development:
  bucket_name: recordings.idapted.com
  access_key_id: 0RWE178RC8Q24C81AAR2
  secret_access_key: U82ZuNP2Fbux+OGzZ+Qurcg0pG7dfDeeTCu2wOKt

test:
  bucket_name: recordings.idapted.com
  access_key_id: 0RWE178RC8Q24C81AAR2
  secret_access_key: U82ZuNP2Fbux+OGzZ+Qurcg0pG7dfDeeTCu2wOKt

production:
  bucket_name: recordings.idapted.com
  access_key_id: 0RWE178RC8Q24C81AAR2
  secret_access_key: U82ZuNP2Fbux+OGzZ+Qurcg0pG7dfDeeTCu2wOKt
