development:
  adapter: mysql
  database: zhangzhe_development
  username: root
  password: 
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: zhangzhe_development
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: zhangzhe_bf
  username: root
  password: 
  host: localhost
