development:
  adapter: mysql
  database: zhangzhe_development
  username: root
  password: 
  host: localhost


test:
  adapter: mysql
  database: zhangzhe_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: zhangzhe_production
  username: root
  password: 
  host: localhost
